config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

 root 'fixed_pages#home'

  get 'faq' => 'fixed_pages#faq'

  get 'about' => 'fixed_pages#about'


  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
get 'dashboard' => 'leases#dashboard'
  get 'accept' => 'leases#accept'
#get 'edit' => 'books#edit'
  resources :users 

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :books                

  resources :leases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update] 
  before_action :check_expiration, only: [:edit, :update]
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:primary] = "Email sent with password reset information"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if password_blank?
      flash.now[:alert] = "password cant be blank"
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  #Returns true if password is blank
  def password_blank?
    params[:user][:password].blank?
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end
  #confirms a valid user
  def valid_user
    unless (@user && @user.activated? &&
           @user.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end
  def check_expiration
    if @user.password_reset_expired?
      flash[:alert] = "Password reset has expired."
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "ResetPassword") %>
<div class="medium-6 columns medium-offset-3">
    <h1> Reset Password</h1>
    <div class="callout">
        <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>

            <%= f.label :password %>
            <%= f.password_field :password %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation %>
            <%= f.submit "Update password", class: "button large" %>
        <% end %>
    </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<div class="medium-6 columns medium-offset-3">
    <h1>Forgot password</h1>
    <div class="callout">
        <%= form_for(:password_reset, url: password_resets_path) do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email %>
            <%= f.submit "Submit", class: "Large button" %>
        <% end %>
    </div>
</div>