config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

 root 'fixed_pages#home'

  get 'faq' => 'fixed_pages#faq'

  get 'about' => 'fixed_pages#about'


  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
get 'dashboard' => 'leases#dashboard'
  get 'accept' => 'leases#accept'
#get 'edit' => 'books#edit'
  resources :users 

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :books                

  resources :leases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  require 'AfricasTalkingGateway'
  has_many :books, through: :leases
  has_many :leases
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length:{ maximum: 50 }
  validates :mobile_number, presence: true, length: { minimum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 250},
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  #returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  #Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  #ends activation email
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  #sets the password resets attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  #sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def send_request_approval
    UserMailer.request_approval(self).deliver_now
  end
  #forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end
  #returns true if password reset hass expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  def send_sms(message)
    username = ENV['MY_USERNAME']
    apikey = ENV['MY_API']
    #introduce country code into mobile number if the previous number did not have it
    first_digit = mobile_number[0]
    if first_digit == '0'
      mobile_number[0] = '+254'
    end
    gateway = AfricasTalkingGateway.new(username, apikey)
    begin
      reports = gateway.sendMessage(mobile_number, message)
      reports.each { |x|
        #status is either success or error
        puts 'number=' + x.mobile_number + ';status=' + x.status + ';messageId=' + x.messageId + ';cost=' + x.cost
        puts 'number=' + x.number + ';status=' + x.status + ';messageId=' + x.messageId + ';cost=' + x.cost

      }
    rescue AfricasTalkingGGatewayException => ex
      puts 'Encountered an error:' + ex.message
    end
  end
  private
  #converts email to all lower_case
  def downcase_email
    self.email = email.downcase
  end

  #creates and assigns the activation token and digest
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_captcha, only: [:create]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find_by(id: params[:id])
    @books = Book.where(available: true )
    @books = Book.search(params[:search]) if params[:search]
    @borrowed = @user.leases.borrowed 
  end

  def create 
    @user = User.new(user_params)
    puts @user
    puts @user.valid?
    if @user.save
      @user.send_activation_email
      flash[:primary] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :mobile_number)
  end
  #confirms a logged in user
  def logged_in_user
    unless logged_in?
      store_location
      flash[:alert] = "You have to log in first!"
      redirect_to login_url
    end
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.present? && current_user.admin?
  end
  # def check_captcha
  #   unless verify_recaptcha
  #     render 'new'
  #   end
  # end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin_user?
    current_user.admin?
  end

  def gravatar_for(user, options= { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<li>
    <%= gravatar_for user, size: 50 %>
    <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user?(user) %>
        | <%= link_to "delete", user, method: :delete, 
            data: { confirm: "Are You Sure?" } %>
    <% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, "Edit Profile") %>
<h1> Edit your profile </h1>
<div class="row">
    <div class="medium-4 columns medium-offset-4">
        <div class="callout">
            <%= form_for @user do |f|%>
                <%= render 'shared/error_messages', object: f.object %>
                <%= f.label :name %>
                <%= f.text_field :name%>
                <%= f.label :email%>
                <%= f.email_field :email%>
                <%= f.label :password%>
                <%= f.password_field :password%>
                <%= f.label :password_confirmation%>
                <%= f.password_field :password%>
                <%=f.submit "Submit" %>
            <% end %>
            <div class="gravatar_edit">
                <%= gravatar_for @user %>
                <a href="http://gravatar.com/emails" target=_blank>change</a>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1> All Users</h1>
<%= will_paginate %>
<p>This is the list of our esteemed clients</p>
<%= render @users %>
<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, "signUp") %>
<div class="medium-4 columns medium-offset-4">
    <div class="callout">
        <h1> Sign Up</h1>
        <%= form_for @user do |f|%>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name%>
            <%= f.label :email%>
            <%= f.email_field :email%>
            <%= f.label :password%>
            <%= f.password_field :password%>
            <%= f.label :password_confirmation%>
            <%= f.password_field :password_confirmation%>
            <%= f.label :mobile_number %>
            <%= f.text_field :mobile_number %>
            <%# <%= recaptcha_tags %1> %>
            <%=f.submit  "signup", class: "button button large" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
    <div class="medium-4 columns">
        <%= gravatar_for @user %>
        <h4>Hello, <%= @user.name %></h4>
        <h5> Welcome to the E-LIBRARY platform</h5>
    </div>
</div>
<div class="row">
    <div class="row">
        <div class="medium-8 columns">
            <%=form_tag user_path(current_user), method: :get do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Books" %>
        </div>
        <div class="medium-4 columns">
            <%= submit_tag "Search", :name => nil, class: "button expanded " %>
        <% end %>
        </div>
    </div>
    <div class="medium-6 columns">
        <h3> List of the books available </h3>
        <table>
            <tr>
                <th>ISBN</th>
                <th>TITLE</th>
                <th>DESCRIPTION</th>
            </tr>
            <% @books.each do |book| %>
                <% unless current_user.books.include? book %>
                    <tr>
                        <td><%= book.ISBN %></td>
                        <td><%= book.title %></td>
                        <td><%= book.description %></td>
                        <td><%= form_for @user.leases.build do |f| %>
                            <%= f.hidden_field :book_id, value: book.id %>
                            <%= f.hidden_field :user_id %>
                            <%= f.submit "Request", class: "button large" %></td>
                    </tr>
                <% end %>
                <% end %>
        <% end %>
        </table>
    </div>
    <div class="medium-6 columns">
        <h3>List of the borrowed books</h3>
        <table>
            <tr>
                <th>ISBN</th>
                <th>TITLE</th>
                <th>DESCRIPTION</th>
                <th>Due Date</th>
                <th> Charge Fee</th>
            </tr>
            <% @borrowed.each do |borrowed| %>
                <tr>
                    <td><%= borrowed.book.ISBN %></td>
                    <td><%= borrowed.book.title %></td>
                    <td><%= borrowed.book.description %></td>
                    <td> <%= remaining_days(borrowed) unless borrowed.due_date.nil? %></td>
                    <%# <td> <%= fine(borrowed)  %1></td> %>
                </tr>
            <% end %>
        </table>
    </div>
</div>