config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

 root 'fixed_pages#home'

  get 'faq' => 'fixed_pages#faq'

  get 'about' => 'fixed_pages#about'


  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
get 'dashboard' => 'leases#dashboard'
  get 'accept' => 'leases#accept'
#get 'edit' => 'books#edit'
  resources :users 

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :books                

  resources :leases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/fixed_pages_controller.rb
class FixedPagesController < ApplicationController
  def home
    if logged_in?
      @leases = current_user.leases.borrowed
    end
  end

  def faq
  end

  def about
  end

  def contact
  end
end

app/helpers/fixed_pages_helper.rb
module FixedPagesHelper
end

app/views/fixed_pages/about.html.erb
<%=provide(:title, "About")%>
<sectioni id="about">
<div class="row">
    <h1><u>Know Your Library</u></h1>
    <div class="medium-4 columns about">
        <h3>Our Services</h3>
        <h5>E-Library app is an online library management system in which the users: 
        <ul>
            <li> Can view all the books available</li>
            <li> Borrow an available book</li>
            <li> Get emailed if a book is due and not yet returned</li>
            <li> Search for any books available by title</li>
        </ul>
        </h5>
    </div>
    <div class="medium-4 columns about">
        <h3>A bit of History</h3>
        <h5>The online community was officially launched on 18/04/2016
            in Maseno. Its main aim being to easily manage books
            in the local library community.Founders-:
            <ol>
                <li>Shedrack Kivuva</li>
                <li>StellaMaris</li>
                <li>Rachel Mwatela</li>
                <li>Dennis Ochieng</li>
            </ol>
        </h5>
    </div>
    <div class="medium-4 columns about">
        <h3>The community</h3>
        <h5>We are non-profit organisation.The services offered are available to the community. We believe that knowledge 
            is power and therefore do not lock out anyone from enjoying our services. To start enjoying
            our services all you need is to create an account and then comply to our terms and conditions. Creating an account is free</h5>
    </div>
</div>
<section class="team">
    <h1><u>Meet Our Awesome Team</u></h1>
    <div class="row">
        <div class="medium-3 columns">
            <h5>Shecdrak Kivuva</h5>
            <p>He is the community manager. He has an expertise in management from University of 
            Capetown</p>
            <p><i class="fa fa-phone"></i>: 07123456</p>
        </div>
        <div class="medium-3 columns">
            <h5>Rachel Mwatela</h5>
            <p>Operations manager. She is on the forefront in ensuring that customers are 
            satisfied with our services</p>
            <p><i class="fa fa-phone"></i>:789456</p>
        </div>
        <div class="medium-3 columns">
            <h5>Dennis Ochieng</h5>
            <p>Record keeping is his thing. Ensures that everything in the lib is in good order</p>
            <p><i class="fa fa-phone"></i>:963852</p>
        </div>
        <div class="medium-3 columns">
            <h5>StellaMaris Njage</h5>
            <p>Research analyst. Ensures that the most recent books in the market are available in the library.</p>
            <p><i class="fa fa-phone"></i>:456123</p>
        </div>
    </div>
</section>
</section>

app/views/fixed_pages/faq.html.erb
<%= provide(:title, "FAQ") %>
<b><p>1. How many books can one borrow?</p></b>
<p>You can borrow a maximum of five books. The books however, have to be unique</p>
<b><p>2. What do i do to start enjoying your services</p></b>
<p>Just visit the signup to create an account ans start enjoying sevices</p>
<b><p>3. For how long should i stay before returning a book</p></b>
<p> 2 weeks. After that thewe will be a fine of 20/= day </p>

    

app/views/fixed_pages/home.html.erb
<%= provide(:title, "Home") %>
<div class="row">
    <% if logged_in? %>
        <div class="medium-4 columns medium-offset-4">
            <%= render 'shared/user_info' %>
        </div>
    <% else %>
        <div class="medium-2 columns"></div>
        <div class="medium-10 columns">
            <%= image_tag("lib.jpeg", :alt => "first image") %>
            <h1>Welcome to E-Library community</h1>
            <h4>Learn It Live It at your own comfort </h4>
            <h4>Are you a new user?Signup to start enjoying ours services</h4>
            <%=link_to fa_icon('sign-in', text: "SignUp"), new_user_url, class: " button button large" %>
        </div>
    <% end %>
</div>