config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

 root 'fixed_pages#home'

  get 'faq' => 'fixed_pages#faq'

  get 'about' => 'fixed_pages#about'


  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
get 'dashboard' => 'leases#dashboard'
  get 'accept' => 'leases#accept'
#get 'edit' => 'books#edit'
  resources :users 

  resources :account_activations, only: [:edit]

  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :books                

  resources :leases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="columns " id="footer">
    <footer class="callout primary small " >
         designed by @StlMaris123 #code90 2016
         <div class="footericons">
        <%= link_to fa_icon('facebook-square'),'https://www.facebook.com/stella.njage' %>
        <%= link_to fa_icon('github'),'https://github.com/StlMaris123' %>
        <%= link_to fa_icon('twitter'), 'https://twitter.com/StlMaris' %>
        </div>
    </footer>
</div>

app/views/layouts/_header.html.erb
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="menu">
            <li class="menu-text"><strong><%= link_to "E-Libray", root_url%></strong></li>
        </ul>
    </div>

    <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>

            <li><%= link_to fa_icon('home', text: "Home"), root_url %></li>
            <li><%= link_to fa_icon('question-circle', text: "FAQ"), faq_url %></li>
            <li><%= link_to fa_icon('info-circle', text: "About"), about_url%></li>
            <% if logged_in? %>
                <li><%= link_to fa_icon('users', text: "Users"), users_path %></li>
                <% if admin_user? %>
                <li><%= link_to fa_icon('book', text: "books"), books_url %></li>
                    <li><%= link_to fa_icon('plus', text: "Add Book"), new_book_path %></li>
                    <li><%= link_to "Requested Books", leases_path%>
                <% end %>
                <li class="dropdown menu">
                    <a >Account</a>
                    <ul class="menu vertical" >
                        <li><%= link_to fa_icon('user', text: "Profile"), current_user %></li>
                        <li><%= link_to fa_icon('cog', text: "Settings"), edit_user_path(current_user) %></li>
                        <li><%= link_to fa_icon('sign-out', text: "Log out"), logout_path, method: "delete" %></li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to fa_icon('sign-in', text: "Log in"), login_path %></li>
            <% end %>
        </ul>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title><%= content_for?(:title) ? yield(:title) : "untilted" %> | Learn it live it</title>

        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body>
        <%= render 'layouts/header' %>
        <div class="row">
            <% flash.each do |message_type, message| %>
                <div class="callout <%= message_type %>">
                    <%= message %>
                </div>
            <% end %>
            <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
    </body>
</html>